<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ReponsesPredefiniesTableSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        DB::table('reponses_predefinies')->insert([
            [
                'id' => 1,
                'question_id' => 9,
                'reponses_predefinies_ordre' => 1,
                'reponses_predefinies_libelle' => "Agroalimentaire",
                'reponses_predefinies_is_radio	' => false,
                'reponses_predefinies_is_checkbox' => true,
            ],[
                'id' => 2,
                'question_id' => 9,
                'reponses_predefinies_ordre' => 2,
                'reponses_predefinies_libelle' => "Banque/Assurance",
                'reponses_predefinies_is_radio	' => false,
                'reponses_predefinies_is_checkbox' => true,
            ],[
                'id' => 3,
                'question_id' => 9,
                'reponses_predefinies_ordre' => 3,
                'reponses_predefinies_libelle' => "Bois/Papier",
                'reponses_predefinies_is_radio	' => false,
                'reponses_predefinies_is_checkbox' => true,
            ],[
                'id' => 4,
                'question_id' => 9,
                'reponses_predefinies_ordre' => 4,
                'reponses_predefinies_libelle' => "Carton",
                'reponses_predefinies_is_radio	' => false,
                'reponses_predefinies_is_checkbox' => true,
            ],[
                'id' => 5,
                'question_id' => 9,
                'reponses_predefinies_ordre' => 5,
                'reponses_predefinies_libelle' => "Imprimerie",
                'reponses_predefinies_is_radio	' => false,
                'reponses_predefinies_is_checkbox' => true,
            ],[
                'id' => 6,
                'question_id' => 9,
                'reponses_predefinies_ordre' => 6,
                'reponses_predefinies_libelle' => "BTP/Materieux de construction",
                'reponses_predefinies_is_radio	' => false,
                'reponses_predefinies_is_checkbox' => true,
            ],[
                'id' => 7,
                'question_id' => 9,
                'reponses_predefinies_ordre' => 7,
                'reponses_predefinies_libelle' => "Chimie/Parachimie",
                'reponses_predefinies_is_radio	' => false,
                'reponses_predefinies_is_checkbox' => true,
            ],[
                'id' => 8,
                'question_id' => 9,
                'reponses_predefinies_ordre' => 8,
                'reponses_predefinies_libelle' => "Commerce/Négoce/Distribution",
                'reponses_predefinies_is_radio	' => false,
                'reponses_predefinies_is_checkbox' => true,
            ],[
                'id' => 9,
                'question_id' => 9,
                'reponses_predefinies_ordre' => 9,
                'reponses_predefinies_libelle' => "Edition/Communication",
                'reponses_predefinies_is_radio	' => false,
                'reponses_predefinies_is_checkbox' => true,
            ],[
                'id' => 10,
                'question_id' => 9,
                'reponses_predefinies_ordre' => 10,
                'reponses_predefinies_libelle' => "Multimédia",
                'reponses_predefinies_is_radio	' => false,
                'reponses_predefinies_is_checkbox' => true,
            ],[
                'id' => 11,
                'question_id' => 9,
                'reponses_predefinies_ordre' => 11,
                'reponses_predefinies_libelle' => "Banque/Assurance",
                'reponses_predefinies_is_radio	' => false,
                'reponses_predefinies_is_checkbox' => true,
            ],[
                'id' => 12,
                'question_id' => 9,
                'reponses_predefinies_ordre' => 12,
                'reponses_predefinies_libelle' => "Electronique/Electricité",
                'reponses_predefinies_is_radio	' => false,
                'reponses_predefinies_is_checkbox' => true,
            ],[
                'id' => 13,
                'question_id' => 9,
                'reponses_predefinies_ordre' => 13,
                'reponses_predefinies_libelle' => "Etudes et Conseils",
                'reponses_predefinies_is_radio	' => false,
                'reponses_predefinies_is_checkbox' => true,
            ],[
                'id' => 14,
                'question_id' => 9,
                'reponses_predefinies_ordre' => 14,
                'reponses_predefinies_libelle' => "Industrie pharmaceutique",
                'reponses_predefinies_is_radio	' => false,
                'reponses_predefinies_is_checkbox' => true,
            ],[
                'id' => 15,
                'question_id' => 9,
                'reponses_predefinies_ordre' => 15,
                'reponses_predefinies_libelle' => "Informatique/Télécoms",
                'reponses_predefinies_is_radio	' => false,
                'reponses_predefinies_is_checkbox' => true,
            ],[
                'id' => 16,
                'question_id' => 9,
                'reponses_predefinies_ordre' => 16,
                'reponses_predefinies_libelle' => "Machines et équipements/Automobile",
                'reponses_predefinies_is_radio	' => false,
                'reponses_predefinies_is_checkbox' => true,
            ],[
                'id' => 17,
                'question_id' => 9,
                'reponses_predefinies_ordre' => 17,
                'reponses_predefinies_libelle' => "Métallurgie/Travail du métal",
                'reponses_predefinies_is_radio	' => false,
                'reponses_predefinies_is_checkbox' => true,
            ],[
                'id' => 18,
                'question_id' => 9,
                'reponses_predefinies_ordre' => 18,
                'reponses_predefinies_libelle' => "BTP/Materieux de construction",
                'reponses_predefinies_is_radio	' => false,
                'reponses_predefinies_is_checkbox' => true,
            ],[
                'id' => 19,
                'question_id' => 9,
                'reponses_predefinies_ordre' => 19,
                'reponses_predefinies_libelle' => "Plastique/Caoutchouc",
                'reponses_predefinies_is_radio	' => false,
                'reponses_predefinies_is_checkbox' => true,
            ],[
                'id' => 20,
                'question_id' => 9,
                'reponses_predefinies_ordre' => 20,
                'reponses_predefinies_libelle' => "Services aux entreprises",
                'reponses_predefinies_is_radio	' => false,
                'reponses_predefinies_is_checkbox' => true,
            ],[
                'id' => 21,
                'question_id' => 9,
                'reponses_predefinies_ordre' => 21,
                'reponses_predefinies_libelle' => "Textile/Habillement/Chaussure",
                'reponses_predefinies_is_radio	' => false,
                'reponses_predefinies_is_checkbox' => true,
            ],[
                'id' => 22,
                'question_id' => 9,
                'reponses_predefinies_ordre' => 22,
                'reponses_predefinies_libelle' => "Transports/Logistique ",
                'reponses_predefinies_is_radio	' => false,
                'reponses_predefinies_is_checkbox' => true,
            ],[
                'id' => 23,
                'question_id' => 13,
                'reponses_predefinies_ordre' => 1,
                'reponses_predefinies_libelle' => "CDI",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 24,
                'question_id' => 13,
                'reponses_predefinies_ordre' => 2,
                'reponses_predefinies_libelle' => "CDD",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 25,
                'question_id' => 13,
                'reponses_predefinies_ordre' => 3,
                'reponses_predefinies_libelle' => "Intérimaire",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 26,
                'question_id' => 13,
                'reponses_predefinies_ordre' => 4,
                'reponses_predefinies_libelle' => "Apprenti",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 27,
                'question_id' => 13,
                'reponses_predefinies_ordre' => 5,
                'reponses_predefinies_libelle' => "Autres",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 28,
                'question_id' => 14,
                'reponses_predefinies_ordre' => 1,
                'reponses_predefinies_libelle' => "Technicien",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 29,
                'question_id' => 14,
                'reponses_predefinies_ordre' => 2,
                'reponses_predefinies_libelle' => "Ingénieur",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 30,
                'question_id' => 14,
                'reponses_predefinies_ordre' => 3,
                'reponses_predefinies_libelle' => "Cadre",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 31,
                'question_id' => 14,
                'reponses_predefinies_ordre' => 4,
                'reponses_predefinies_libelle' => "Autres",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 32,
                'question_id' => 16,
                'reponses_predefinies_ordre' => 1,
                'reponses_predefinies_libelle' => "Oui",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 33,
                'question_id' => 16,
                'reponses_predefinies_ordre' => 2,
                'reponses_predefinies_libelle' => "Non",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 34,
                'question_id' => 18,
                'reponses_predefinies_ordre' => 1,
                'reponses_predefinies_libelle' => "SAS",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 35,
                'question_id' => 18,
                'reponses_predefinies_ordre' => 2,
                'reponses_predefinies_libelle' => "SARL",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 36,
                'question_id' => 18,
                'reponses_predefinies_ordre' => 3,
                'reponses_predefinies_libelle' => "SA",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 37,
                'question_id' => 18,
                'reponses_predefinies_ordre' => 4,
                'reponses_predefinies_libelle' => "PME",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 38,
                'question_id' => 18,
                'reponses_predefinies_ordre' => 5,
                'reponses_predefinies_libelle' => "Auto Entrepreneur",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 39,
                'question_id' => 18,
                'reponses_predefinies_ordre' => 6,
                'reponses_predefinies_libelle' => "Autres",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 40,
                'question_id' => 19,
                'reponses_predefinies_ordre' => 1,
                'reponses_predefinies_libelle' => "Oui",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 41,
                'question_id' => 19,
                'reponses_predefinies_ordre' => 2,
                'reponses_predefinies_libelle' => "Non",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 42,
                'question_id' => 22,
                'reponses_predefinies_ordre' => 1,
                'reponses_predefinies_libelle' => "Oui",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 43,
                'question_id' => 22,
                'reponses_predefinies_ordre' => 2,
                'reponses_predefinies_libelle' => "Non",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 44,
                'question_id' => 29,
                'reponses_predefinies_ordre' => 1,
                'reponses_predefinies_libelle' => "Oui",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 45,
                'question_id' => 29,
                'reponses_predefinies_ordre' => 2,
                'reponses_predefinies_libelle' => "Non",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 46,
                'question_id' => 30,
                'reponses_predefinies_ordre' => 1,
                'reponses_predefinies_libelle' => "Seul",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 47,
                'question_id' => 30,
                'reponses_predefinies_ordre' => 2,
                'reponses_predefinies_libelle' => "Sous responsabilité",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 48,
                'question_id' => 33,
                'reponses_predefinies_ordre' => 1,
                'reponses_predefinies_libelle' => "CDI",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 49,
                'question_id' => 33,
                'reponses_predefinies_ordre' => 2,
                'reponses_predefinies_libelle' => "CDD",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 50,
                'question_id' => 33,
                'reponses_predefinies_ordre' => 3,
                'reponses_predefinies_libelle' => "Intérimaire",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 51,
                'question_id' => 33,
                'reponses_predefinies_ordre' => 4,
                'reponses_predefinies_libelle' => "Apprenti",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 52,
                'question_id' => 33,
                'reponses_predefinies_ordre' => 5,
                'reponses_predefinies_libelle' => "Autres",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 53,
                'question_id' => 34,
                'reponses_predefinies_ordre' => 1,
                'reponses_predefinies_libelle' => "Technicien",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 54,
                'question_id' => 34,
                'reponses_predefinies_ordre' => 2,
                'reponses_predefinies_libelle' => "Ingénieur",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 55,
                'question_id' => 34,
                'reponses_predefinies_ordre' => 3,
                'reponses_predefinies_libelle' => "Cadre",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 56,
                'question_id' => 34,
                'reponses_predefinies_ordre' => 4,
                'reponses_predefinies_libelle' => "Autres",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 57,
                'question_id' => 36,
                'reponses_predefinies_ordre' => 1,
                'reponses_predefinies_libelle' => "Oui",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 58,
                'question_id' => 36,
                'reponses_predefinies_ordre' => 2,
                'reponses_predefinies_libelle' => "Non",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 59,
                'question_id' => 38,
                'reponses_predefinies_ordre' => 1,
                'reponses_predefinies_libelle' => "SAS",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 60,
                'question_id' => 38,
                'reponses_predefinies_ordre' => 2,
                'reponses_predefinies_libelle' => "SARL",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 61,
                'question_id' => 38,
                'reponses_predefinies_ordre' => 3,
                'reponses_predefinies_libelle' => "SA",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 62,
                'question_id' => 38,
                'reponses_predefinies_ordre' => 4,
                'reponses_predefinies_libelle' => "PME",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 63,
                'question_id' => 38,
                'reponses_predefinies_ordre' => 5,
                'reponses_predefinies_libelle' => "Auto Entrepreneur",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 64,
                'question_id' => 38,
                'reponses_predefinies_ordre' => 6,
                'reponses_predefinies_libelle' => "Autres",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 65,
                'question_id' => 39,
                'reponses_predefinies_ordre' => 1,
                'reponses_predefinies_libelle' => "Oui",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 66,
                'question_id' => 39,
                'reponses_predefinies_ordre' => 2,
                'reponses_predefinies_libelle' => "Non",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 67,
                'question_id' => 42,
                'reponses_predefinies_ordre' => 1,
                'reponses_predefinies_libelle' => "Oui",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 68,
                'question_id' => 42,
                'reponses_predefinies_ordre' => 2,
                'reponses_predefinies_libelle' => "Non",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 69,
                'question_id' => 49,
                'reponses_predefinies_ordre' => 1,
                'reponses_predefinies_libelle' => "Oui",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 70,
                'question_id' => 49,
                'reponses_predefinies_ordre' => 2,
                'reponses_predefinies_libelle' => "Non",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 71,
                'question_id' => 50,
                'reponses_predefinies_ordre' => 1,
                'reponses_predefinies_libelle' => "Seul",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 72,
                'question_id' => 50,
                'reponses_predefinies_ordre' => 2,
                'reponses_predefinies_libelle' => "Sous responsabilité",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 73,
                'question_id' => 52,
                'reponses_predefinies_ordre' => 1,
                'reponses_predefinies_libelle' => "Oui",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 74,
                'question_id' => 52,
                'reponses_predefinies_ordre' => 2,
                'reponses_predefinies_libelle' => "Non",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 75,
                'question_id' => 53,
                'reponses_predefinies_ordre' => 1,
                'reponses_predefinies_libelle' => "Oui",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 76,
                'question_id' => 53,
                'reponses_predefinies_ordre' => 2,
                'reponses_predefinies_libelle' => "Non",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 77,
                'question_id' => 56,
                'reponses_predefinies_ordre' => 1,
                'reponses_predefinies_libelle' => "Oui",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],[
                'id' => 78,
                'question_id' => 56,
                'reponses_predefinies_ordre' => 2,
                'reponses_predefinies_libelle' => "Non",
                'reponses_predefinies_is_radio	' => true,
                'reponses_predefinies_is_checkbox' => false,
            ],
        ]);
    }

}